import { CuratedCollection } from './app-dashboard-collections.type';

export const COLLECTION_STATUS_OPTIONS: { value: string; label: string }[] = [
  { value: '', label: 'All Status' },
  { value: 'draft', label: 'Draft' },
  { value: 'published', label: 'Published' },
];

export const MOCK_COLLECTIONS: CuratedCollection[] = [
  {
    uuid: 'col-uuid-01',
    name: 'Collection 1',
    user_roles: ['Guest', 'Admin', 'Manager'],
    user_groups: ['Guest', 'Team Alpha', 'Team Beta'],
    created_by: 'Emily Johnson',
    updated_at: '2025-05-22',
    status: 'draft',
  },
  {
    uuid: 'col-uuid-02',
    name: 'Collection 2',
    user_roles: ['Admin', 'Super Admin', 'Manager'],
    user_groups: ['Admin', 'Ops Team', 'Dev Team'],
    created_by: 'Michael Smith',
    updated_at: '2025-05-05',
    status: 'published',
  },
  {
    uuid: 'col-uuid-03',
    name: 'Collection 3',
    user_roles: ['Super Admin', 'Admin', 'Guest'],
    user_groups: ['Super Admin', 'Team Gamma', 'Team Delta'],
    created_by: 'Jessica Brown',
    updated_at: '2025-05-12',
    status: 'published',
  },
  {
    uuid: 'col-uuid-04',
    name: 'Collection 4',
    user_roles: ['Guest', 'Admin'],
    user_groups: ['Guest', 'Team Alpha'],
    created_by: 'David Wilson',
    updated_at: '2025-05-18',
    status: 'draft',
  },
  {
    uuid: 'col-uuid-05',
    name: 'Collection 5',
    user_roles: ['Super Admin', 'Admin', 'Manager', 'Guest'],
    user_groups: ['Super Admin', 'Ops Team', 'Dev Team', 'QA Team'],
    created_by: 'Sarah Davis',
    updated_at: '2025-05-15',
    status: 'draft',
  },
  {
    uuid: 'col-uuid-06',
    name: 'Collection 6',
    user_roles: ['Guest', 'Admin', 'Manager'],
    user_groups: ['Guest', 'Team Beta', 'Team Gamma'],
    created_by: 'James Miller',
    updated_at: '2025-05-21',
    status: 'draft',
  },
  {
    uuid: 'col-uuid-07',
    name: 'Collection 7',
    user_roles: ['Admin', 'Super Admin', 'Guest'],
    user_groups: ['Admin', 'Dev Team', 'QA Team'],
    created_by: 'Ashley Garcia',
    updated_at: '2025-05-19',
    status: 'published',
  },
  {
    uuid: 'col-uuid-08',
    name: 'Collection 8',
    user_roles: ['Guest', 'Admin', 'Manager', 'Viewer'],
    user_groups: ['Guest', 'Team Alpha', 'Ops Team', 'Dev Team'],
    created_by: 'Christopher Martinez',
    updated_at: '2025-05-10',
    status: 'draft',
  },
  {
    uuid: 'col-uuid-09',
    name: 'Collection 9',
    user_roles: ['Admin', 'Super Admin', 'Manager'],
    user_groups: ['Admin', 'Team Delta', 'QA Team'],
    created_by: 'Amanda Rodriguez',
    updated_at: '2025-05-07',
    status: 'draft',
  },
  {
    uuid: 'col-uuid-10',
    name: 'Collection 10',
    user_roles: ['Super Admin', 'Admin', 'Guest'],
    user_groups: ['Super Admin', 'Ops Team', 'Dev Team'],
    created_by: 'Daniel Hernandez',
    updated_at: '2025-05-14',
    status: 'published',
  },
  {
    uuid: 'col-uuid-11',
    name: 'Collection 11',
    user_roles: ['Guest', 'Admin'],
    user_groups: ['Guest', 'Team Beta'],
    created_by: 'Olivia Thompson',
    updated_at: '2025-05-03',
    status: 'draft',
  },
  {
    uuid: 'col-uuid-12',
    name: 'Collection 12',
    user_roles: ['Admin', 'Manager', 'Viewer'],
    user_groups: ['Admin', 'Dev Team', 'QA Team'],
    created_by: 'Ethan White',
    updated_at: '2025-05-08',
    status: 'published',
  },
  {
    uuid: 'col-uuid-13',
    name: 'Collection 13',
    user_roles: ['Super Admin', 'Admin', 'Guest', 'Viewer'],
    user_groups: ['Super Admin', 'Team Gamma', 'Ops Team', 'Dev Team'],
    created_by: 'Sophia Lee',
    updated_at: '2025-05-17',
    status: 'draft',
  },
  {
    uuid: 'col-uuid-14',
    name: 'Collection 14',
    user_roles: ['Guest', 'Admin', 'Manager'],
    user_groups: ['Guest', 'QA Team', 'Team Alpha'],
    created_by: 'Liam Walker',
    updated_at: '2025-05-20',
    status: 'published',
  },
  {
    uuid: 'col-uuid-15',
    name: 'Collection 15',
    user_roles: ['Admin', 'Super Admin'],
    user_groups: ['Admin', 'Ops Team'],
    created_by: 'Mia Harris',
    updated_at: '2025-05-11',
    status: 'draft',
  },
  {
    uuid: 'col-uuid-16',
    name: 'Collection 16',
    user_roles: ['Super Admin', 'Admin', 'Guest'],
    user_groups: ['Super Admin', 'Dev Team', 'Team Delta'],
    created_by: 'Noah Clark',
    updated_at: '2025-05-16',
    status: 'published',
  },
];
